version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
          
      - restore_cache:
          keys:
            - unity

      # Build the app and run tests
      - run:
          name: install Unity
          environment:
            PROJECT_ROOT: $PWD/tap_project
            UNITY_DOWNLOAD_DIR: $PROJECT_ROOT/unity
            UNITY_PKG_LOCATION: $UNITY_DOWNLOAD_DIR/Unity.pkg
            UNITY_PKG_URL: https://download.unity3d.com/download_unity/5d30cf096e79/MacEditorInstaller/Unity-2017.1.1f1.pkg
            IOS_PKG_LOCATION: $UNITY_DOWNLOAD_DIR/Unity-iOS.pkg
            IOS_PKG_URL: http://netstorage.unity3d.com/unity/5d30cf096e79/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor.pkg
            UNITY_CIRCLE_XML_DIR: $CIRCLE_TEST_REPORTS/Unity
            UNITY_CIRCLE_XML_OUT_PATH: $UNITY_CIRCLE_XML_DIR/junit.xml
          command: ./scripts/install_unity.sh
      
      - save_cache:
          key: unity
          paths:
            - unity


workflows:
  version: 2
  install_and_build:
    jobs:
      - build:
          filters:
            branches:
              only: master
