version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run:
        name: interpolating environment variables
        command: |
          echo 'export UNITY_DOWNLOAD_DIR=/path/:$PROJECT_ROOT'
          
      - restore_cache:
          keys:
            - unity

      # Install Unity and iOS Editor
      - run:
          name: install Unity
          command: ./scripts/install_unity.sh
      
      - save_cache:
          key: unity
          paths:
            - unity
      # Activate unity license
      - run:
          name: activate unity license
          command: ./active_license.sh

workflows:
  version: 2
  install_and_build:
    jobs:
      - build:
          filters:
            branches:
              only: master
